### ISSUE TITLE
Perhitungan Rumus

### ISSUE THREAD

**Issue by sripadu** [imamdigmi/simple-selection-employees-dss-ahp#10]
1. Matris Pebandingan Berpasangan (sudah)
2. Matriks Nilai Kriteria (sudah)

tambahan blm selesai ::
3. Matriks penjumlahan setiap Baris
4. Perhitungan Rasio Kosistensi

**Comment by imamdigmi** [comment]
udah di test sri?
yg tambahan itu maksudnya rumus nya belum atau cuman belum tampil doang?

**Comment by sripadu** [comment]
rumusnya blm mam kayak di excel itu
