### ISSUE TITLE
nilai awal

### ISSUE THREAD

**Issue by sripadu** [imamdigmi/simple-selection-employees-dss-ahp#20]
Tampilkan semua nilai yang di input, tampilan kyk rata2, periode dan keterangan jadi semua nilai yang di input di tampilkan

**Comment by imamdigmi** [comment]
Ini mah udah ada di halaman nilai awal, udah aku tampilkan juga itu semua nilai yg diinputkan.

**Comment by sripadu** [comment]
Iya udah ada yang ada gambar mata itu kan? Diklik?
Maksudnya aku ditampilkan semua ditampilan kyk rata2, keterangan periode

**Comment by sripadu** [comment]
Iya udah ada yang ada gambar mata itu kan? Diklik?
Maksudnya aku ditampilkan semua ditampilan kyk rata2, keterangan periode
